// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TradingLab.Journal.Infrastructure.Data.Context;

#nullable disable

namespace TradingLab.Journal.Infrastructure.Migrations
{
    [DbContext(typeof(JournalDbContext))]
    [Migration("20260615164543_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TagTrade", b =>
                {
                    b.Property<Guid>("TagsId")
                        .HasColumnType("uuid")
                        .HasColumnName("tags_id");

                    b.Property<Guid>("TradesId")
                        .HasColumnType("uuid")
                        .HasColumnName("trades_id");

                    b.HasKey("TagsId", "TradesId")
                        .HasName("pk_tag_trade");

                    b.HasIndex("TradesId")
                        .HasDatabaseName("ix_tag_trade_trades_id");

                    b.ToTable("tag_trade", (string)null);
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("MarketCondition")
                        .HasColumnType("integer")
                        .HasColumnName("market_condition");

                    b.Property<int>("Mood")
                        .HasColumnType("integer")
                        .HasColumnName("mood");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_journal_entries");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.Position", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AverageEntryPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("average_entry_price");

                    b.Property<decimal>("AverageExitPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("average_exit_price");

                    b.Property<DateTime>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<decimal>("RealizedPnL")
                        .HasColumnType("numeric")
                        .HasColumnName("realized_pn_l");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<decimal>("TotalEntryQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("total_entry_quantity");

                    b.Property<decimal>("TotalExitQuantity")
                        .HasColumnType("numeric")
                        .HasColumnName("total_exit_quantity");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("trading_account_id");

                    b.HasKey("Id")
                        .HasName("pk_positions");

                    b.HasIndex("TradingAccountId")
                        .HasDatabaseName("ix_positions_trading_account_id");

                    b.ToTable("positions", (string)null);
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.Trade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("executed_at");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid")
                        .HasColumnName("position_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric")
                        .HasColumnName("quantity");

                    b.Property<int>("Side")
                        .HasColumnType("integer")
                        .HasColumnName("side");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ticker");

                    b.Property<Guid>("TradingAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("trading_account_id");

                    b.HasKey("Id")
                        .HasName("pk_trades");

                    b.HasIndex("PositionId")
                        .HasDatabaseName("ix_trades_position_id");

                    b.HasIndex("TradingAccountId")
                        .HasDatabaseName("ix_trades_trading_account_id");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.TradeNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("TradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("trade_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_trade_notes");

                    b.HasIndex("TradeId")
                        .HasDatabaseName("ix_trade_notes_trade_id");

                    b.ToTable("trade_notes", (string)null);
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.TradingAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_trading_accounts");

                    b.ToTable("trading_accounts", (string)null);
                });

            modelBuilder.Entity("TagTrade", b =>
                {
                    b.HasOne("TradingLab.Journal.Domain.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_trade_tags_tags_id");

                    b.HasOne("TradingLab.Journal.Domain.Entities.Trade", null)
                        .WithMany()
                        .HasForeignKey("TradesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tag_trade_trades_trades_id");
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.Position", b =>
                {
                    b.HasOne("TradingLab.Journal.Domain.Entities.TradingAccount", "TradingAccount")
                        .WithMany("Positions")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_positions_trading_accounts_trading_account_id");

                    b.Navigation("TradingAccount");
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.Trade", b =>
                {
                    b.HasOne("TradingLab.Journal.Domain.Entities.Position", "Position")
                        .WithMany("Trades")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_positions_position_id");

                    b.HasOne("TradingLab.Journal.Domain.Entities.TradingAccount", "TradingAccount")
                        .WithMany("Trades")
                        .HasForeignKey("TradingAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trades_trading_accounts_trading_account_id");

                    b.Navigation("Position");

                    b.Navigation("TradingAccount");
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.TradeNote", b =>
                {
                    b.HasOne("TradingLab.Journal.Domain.Entities.Trade", "Trade")
                        .WithMany("Notes")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trade_notes_trades_trade_id");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.Position", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.Trade", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("TradingLab.Journal.Domain.Entities.TradingAccount", b =>
                {
                    b.Navigation("Positions");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
